
########## kubernets file for podman ###########
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-04T21:07:07Z"
  labels:
    app: optimism-node-pod
  name: optimism-node-pod
spec:
  ports:
  - name: "8547"
    nodePort: 30947
    port: 8547
    targetPort: 8547
  - name: "8548"
    nodePort: 31577
    port: 8548
    targetPort: 8548
  - name: "8552"
    nodePort: 31194
    port: 8552
    targetPort: 8552
  - name: "30304"
    nodePort: 31815
    port: 30304
    targetPort: 30304
  - name: "30304"
    nodePort: 30405
    port: 30304
    protocol: UDP
    targetPort: 30304
  - name: "9000"
    nodePort: 30922
    port: 9000
    targetPort: 9000
  - name: "9000"
    nodePort: 31409
    port: 9000
    protocol: UDP
    targetPort: 9000
  - name: "5052"
    nodePort: 32178
    port: 5052
    targetPort: 5052
  - name: "9547"
    nodePort: 30946
    port: 9547
    targetPort: 9547
  selector:
    app: optimism-node-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-04T21:07:07Z"
  labels:
    app: optimism-node-pod
  name: optimism-node-pod
spec:
  containers:
  # todo, change to command: geth ...?
  # - args:
  #   - --http
  #   - --http.corsdomain="*"
  #   - --http.vhosts="*"
  #   - --http.addr
  #   - 0.0.0.0
  #   - --http.port
  #   - 8547
  #   - --authrpc.addr
  #   - 0.0.0.0
  #   - --authrpc.vhosts="*"
  #   - --authrpc.jwtsecret
  #   - /root/.ethereum/jwtsecret
  #   - --networkid=$CHAIN_ID
  #   - --rollup.sequencerhttp=$OP_GETH_SEQUENCER_HTTP
  #   - --ipcdisable
    # - --http
    # - --http.corsdomain
    # - http://localhost
    # - --http.vhosts
    # - localhost,host.containers.internal
    # - --authrpc.vhosts
    # - localhost,host.containers.internal
  - name: op-geth
    command: ['sh', '-c', 'cd /data && sh ./geth-entrypoint']
    # command: ['pwd'] # while we are just testing op-node, do nothing here
    envFrom: 
    - configMapRef:
        name: optimism-node-config

    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101105.3
    ports:
    - containerPort: 8547
    - containerPort: 8548
    - containerPort: 8552
    # not needed, yet? p2p discovery
    - containerPort: 30304
    - containerPort: 30304
      protocol: UDP
    volumeMounts:
    - mountPath: /data
      name: op-geth-vol-optimism
  - name: op-node
    command: ['sh', '-c', 'cd /data && sh ./op-node-entrypoint']
  # - args:
  #   - --l1
  #   - https://eth-mainnet.g.alchemy.com/v2/hlnAhv-Jx2mCmUuusgTvsrdOelOSRbl9
  #   - --l2
  #   - http://op-geth:8552
  #   - --rpc.addr
  #   - 0.0.0.0
  #   - --rpc.port
  #   - 9547
  #   - --l1.trustrpc
  #   - --l2.jwt-secret
  #   - /root/.ethereum/jwtsecret
    # - --authrpc.addr
    # - 0.0.0.0
    # - --ipcdisable
    # - --p2p.disable
    # - --http
    # - --http.corsdomain
    # - http://localhost
    # - --http.vhosts
    # - localhost,host.containers.internal
    # - --authrpc.vhosts
    # - localhost,host.containers.internal
    envFrom:
    - configMapRef:
        name: optimism-node-config
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.1.0
    ports:
    - containerPort: 9547
    - containerPort: 9000
    - containerPort: 9000
      protocol: UDP
    volumeMounts:
    - mountPath: /data
      name: op-node-vol-optimism
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /home/johns/dev/superhack/optimism/workdir/op-geth
      type: Directory
    name: op-geth-vol-optimism
  - hostPath:
      path: /home/johns/dev/superhack/optimism/workdir/op-node
      type: Directory
    name: op-node-vol-optimism
