
########## kubernets file for podman ###########
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-04T21:07:07Z"
  labels:
    app: base-node-pod
  name: base-node-pod
spec:
  ports:
  - name: "8545"
    nodePort: 30947
    port: 8545
    targetPort: 8545
  - name: "8546"
    nodePort: 31577
    port: 8546
    targetPort: 8546
  - name: "8551"
    nodePort: 31194
    port: 8551
    targetPort: 8551
  - name: "30303"
    nodePort: 31815
    port: 30303
    targetPort: 30303
  - name: "30303"
    nodePort: 30405
    port: 30303
    protocol: UDP
    targetPort: 30303
  - name: "9000"
    nodePort: 30922
    port: 9000
    targetPort: 9000
  - name: "9000"
    nodePort: 31409
    port: 9000
    protocol: UDP
    targetPort: 9000
  - name: "5052"
    nodePort: 32178
    port: 5052
    targetPort: 5052
  - name: "9545"
    nodePort: 30946
    port: 9545
    targetPort: 9545
  - name: "9003"
    nodePort: 30945
    port: 9003
    targetPort: 9003
  - name: "9003"
    nodePort: 30944
    port: 9003
    protocol: UDP
    targetPort: 9003
  - name: "9222"
    nodePort: 30000
    port: 9222
    targetPort: 9222
  - name: "9222"
    nodePort: 30001
    port: 9222
    protocol: UDP
    targetPort: 9222
  selector:
    app: base-node-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-04T21:07:07Z"
  labels:
    app: base-node-pod
  name: base-node-pod
spec:
  containers:
  # todo, change to command: geth ...?
  # - args:
  #   - --http
  #   - --http.corsdomain="*"
  #   - --http.vhosts="*"
  #   - --http.addr
  #   - 0.0.0.0
  #   - --http.port
  #   - 8545
  #   - --authrpc.addr
  #   - 0.0.0.0
  #   - --authrpc.vhosts="*"
  #   - --authrpc.jwtsecret
  #   - /root/.ethereum/jwtsecret
  #   - --networkid=$CHAIN_ID
  #   - --rollup.sequencerhttp=$OP_GETH_SEQUENCER_HTTP
  #   - --ipcdisable
    # - --http
    # - --http.corsdomain
    # - http://localhost
    # - --http.vhosts
    # - localhost,host.containers.internal
    # - --authrpc.vhosts
    # - localhost,host.containers.internal
  - name: op-geth
    command: ['sh', '-c', 'cd /data && sh ./geth-entrypoint']
    # command: ['pwd'] # while we are just testing op-node, do nothing here
    envFrom: 
    - configMapRef:
        name: base-node-config

    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101105.3
    ports:
    - containerPort: 8545
    - containerPort: 8546
    - containerPort: 8551
    # not needed, yet? p2p discovery
    - containerPort: 30303
    - containerPort: 30303
      protocol: UDP
    volumeMounts:
    - mountPath: /data
      name: op-geth-vol-1
  - name: op-node
    command: ['sh', '-c', 'cd /data && sh ./op-node-entrypoint']
  # - args:
  #   - --l1
  #   - https://eth-mainnet.g.alchemy.com/v2/hlnAhv-Jx2mCmUuusgTvsrdOelOSRbl9
  #   - --l2
  #   - http://op-geth:8551
  #   - --rpc.addr
  #   - 0.0.0.0
  #   - --rpc.port
  #   - 9545
  #   - --l1.trustrpc
  #   - --l2.jwt-secret
  #   - /root/.ethereum/jwtsecret
    # - --authrpc.addr
    # - 0.0.0.0
    # - --ipcdisable
    # - --p2p.disable
    # - --http
    # - --http.corsdomain
    # - http://localhost
    # - --http.vhosts
    # - localhost,host.containers.internal
    # - --authrpc.vhosts
    # - localhost,host.containers.internal
    envFrom:
    - configMapRef:
        name: base-node-config
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.1.0
    ports:
    - containerPort: 9545
    - containerPort: 9222
    - containerPort: 9222
      protocol: UDP
    volumeMounts:
    - mountPath: /data
      name: op-node-vol-1
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /home/johns/dev/superhack/base/workdir/op-geth
      type: Directory
    name: op-geth-vol-1
  - hostPath:
      path: /home/johns/dev/superhack/base/workdir/op-node
      type: Directory
    name: op-node-vol-1
